root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/gochat ./cmd/gochat/main.go"
bin = "./bin/gochat"
full_bin = "GOCHAT_LLM_API_KEY=${GROQ_API_KEY} ./bin/gochat"
include_ext = ["go", "yaml"]
exclude_dir = ["bin", "tmp", "vendor", "chats"]
delay = 1000 # ms
kill_delay = "0.5s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta" 